#!/usr/bin/env node
'use strict';

// Single source of truth = CLAUDE.md (the 7 principles). This script fans that
// one file out into the rule-file format each agent reads, so every harness
// gets identical guidance. Run `node scripts/build-rules.js` after editing
// CLAUDE.md; CI runs it with `--check` to fail if a copy drifted.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const TITLE = 'Coding-Agent Guidelines (Karpathy-inspired)';
const DESC =
  'Karpathy-inspired coding-agent behavior — think before coding, simplicity, ' +
  'surgical changes, goal-driven execution, recalibrate time, skillify & resolve, ground in reality.';
const NOTE =
  '<!-- AUTOGENERATED from CLAUDE.md by scripts/build-rules.js. ' +
  'Edit CLAUDE.md, then run `npm run build`. Do not edit this file directly. -->';

// Drop the leading "# CLAUDE.md" H1; keep the intro down. The rest is verbatim.
function principlesBody() {
  const src = fs.readFileSync(path.join(ROOT, 'CLAUDE.md'), 'utf8');
  return src.replace(/^#\s+CLAUDE\.md\s*\n+/, '').trimEnd() + '\n';
}

const plain = (body) => `# ${TITLE}\n\n${NOTE}\n\n${body}`;
const cursor = (body) =>
  `---\ndescription: ${DESC}\nglobs:\nalwaysApply: true\n---\n\n# ${TITLE}\n\n${NOTE}\n\n${body}`;

// rel path -> formatter. Plain markdown works for every agent except Cursor,
// which needs .mdc frontmatter (matches the convention in popular skill repos).
const TARGETS = {
  'AGENTS.md': plain,                          // Codex, Amp, Jules, generic AGENTS.md
  'GEMINI.md': plain,                          // Gemini CLI
  '.github/copilot-instructions.md': plain,    // GitHub Copilot
  '.windsurf/rules/karpathy-skills.md': plain, // Windsurf
  '.clinerules/karpathy-skills.md': plain,     // Cline
  '.cursor/rules/karpathy-skills.mdc': cursor, // Cursor
};

function run({ check }) {
  const body = principlesBody();
  const drift = [];
  for (const [rel, fmt] of Object.entries(TARGETS)) {
    const out = fmt(body);
    const abs = path.join(ROOT, rel);
    if (check) {
      const cur = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : '';
      if (cur !== out) drift.push(rel);
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, out);
      console.log('wrote', rel);
    }
  }
  if (check) {
    if (drift.length) {
      console.error(
        'Rule copies are out of sync with CLAUDE.md:\n  ' +
          drift.join('\n  ') +
          '\n\nRun `npm run build` and commit the result.'
      );
      process.exit(1);
    }
    console.log('All rule copies are in sync with CLAUDE.md.');
  }
}

run({ check: process.argv.includes('--check') });
